[package]
name = "callrust"
version = "0.1.0"
authors = ["wangyongf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.77"

[lib]
name = "callrust"
crate-type = ["staticlib", "cdylib"]